# Generated by Django 4.2.5 on 2023-09-25 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='comments',
            new_name='client_comments',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='client_name',
        ),
    ]
